### ISSUE TITLE
Failing to build wxGL DLL Debug with nmake

### ISSUE THREAD

**Issue by PBfordev** [wxWidgets/wxWidgets#26128]
When trying to build the current master (f838eb00bae4e3799de6f7932e49695e4c0f32ac) using the bundled makefile.vc with `nmake -f makefile.vc SHARED=1`, it fails with
```
link /DLL /NOLOGO /OUT:..\..\lib\vc_x64_dll\wxmsw332ud_gl_vc_x64_custom.dll  /DEBUG /pdb:"..\..\lib\vc_x64_dll\wxmsw332ud_gl_vc_x64_custom.pdb"   /MACHINE:X64 /LIBPATH:..\..\lib\vc_x64_dll   @r:\temp\nm1B85.tmp
   Creating library ..\..\lib\vc_x64_dll\wxmsw33ud_gl.lib and object ..\..\lib\vc_x64_dll\wxmsw33ud_gl.exp
gldll_glcmn.obj : error LNK2019: unresolved external symbol _CrtDbgReport referenced in function "void * __cdecl std::_Allocate_manually_vector_aligned<struct std::_Default_allocate_traits>(unsigned __int64)" (??$_Allocate_manually_vector_aligned@U_Default_allocate_traits@std@@@std@@YAPEAX_K@Z)
gldll_glcanvas.obj : error LNK2001: unresolved external symbol _CrtDbgReport
..\..\lib\vc_x64_dll\wxmsw332ud_gl_vc_x64_custom.dll : fatal error LNK1120: 1 unresolved externals
NMAKE : fatal error U1077: 'link /DLL /NOLOGO /OUT:..\..\lib\vc_x64_dll\wxmsw332ud_gl_vc_x64_custom.dll  /DEBUG /pdb:"..\..\lib\vc_x64_dll\wxmsw332ud_gl_vc_x64_custom.pdb"   /MACHINE:X64 /LIBPATH:..\..\lib\vc_x64_dll   @r:\temp\nm1B85.tmp' : return code '0x460'
```

Used latest MSVS 2022 and 2026, `setup.h` was not modifed. The DLL Release as well as static configurations build fine.

When using CMake or the bundled MSVS solution, there is no problem.

GIT bisect points to 6228eaf4494702a13d4538a1694daebab4ddb0b7 as the culprit. There have been changes in the makefile, but I did not notice anything obviously wrong (I know nothing about makefiles).

**Comment by MaartenBent** [comment]
I haven't tried to build it yet with nmake, but after I rebake the build files there is 1 small change in `makefile.vc` related to `gl`:
Does that fix it?
```diff
diff --git "a/build/msw/makefile.vc" "b/build/msw/makefile.vc"
index 64453a98641..f5d12b6dec1 100644
--- "a/build/msw/makefile.vc"
+++ "b/build/msw/makefile.vc"
@@ -2046,7 +2046,7 @@ STCLIB_OBJECTS =  \
 	$(OBJS)\stclib_ScintillaWX.obj \
 	$(OBJS)\stclib_xh_styledtextctrl.obj \
 	$(OBJS)\stclib_minimap.obj
-GLDLL_CXXFLAGS = /M$(__RUNTIME_LIBS_642)$(__DEBUGRUNTIME) /DWIN32 \
+GLDLL_CXXFLAGS = /M$(__RUNTIME_LIBS_657)$(__DEBUGRUNTIME) /DWIN32 \
 	/I..\..\src\tiff\libtiff /I..\..\src\jpeg /I..\..\src\png \
 	/I..\..\3rdparty\libwebp\src $(____INC_LUNASVG_FILENAMES) /I..\..\src\zlib \
 	/I..\..\3rdparty\pcre\src\wx /I..\..\src\expat\expat\lib $(__DEBUGINFO) \
```

**Comment by PBfordev** [comment]
@MaartenBent, thanks for the quick reply and providing the solution. It fixed the issue.

**Comment by vadz** [comment]
I don't know how it happened but the makefiles have indeed been broken in this commit. I'll push the fix in a moment, thanks for noticing it.
