### PR TITLE
Use std::isnan() on C++ 11 compiler

### PR DESCRIPTION
**Pull request by bdrung**
Audacity fails to build on Ubuntu 16.04 with g++ 5.3.1:

```
In file included from /usr/include/wx-3.0/wx/gdicmn.h:23:0,
                 from /usr/include/wx-3.0/wx/utils.h:26,
                 from BlockFile.cpp:51:
BlockFile.cpp: In function ‘void ComputeMinMax256(float*, float*, float*, int*)’:
/usr/include/wx-3.0/wx/math.h:91:31: error: ‘isnan’ was not declared in this scope
     #define wxIsNaN(x) isnan(x)
                               ^
BlockFile.cpp:325:11: note: in expansion of macro ‘wxIsNaN’
       if (wxIsNaN(summary256[3*i+2]))
           ^
/usr/include/wx-3.0/wx/math.h:91:31: note: suggested alternative:
     #define wxIsNaN(x) isnan(x)
                               ^
BlockFile.cpp:325:11: note: in expansion of macro ‘wxIsNaN’
       if (wxIsNaN(summary256[3*i+2]))
           ^
In file included from /usr/include/wx-3.0/wx/math.h:58:0,
                 from /usr/include/wx-3.0/wx/gdicmn.h:23,
                 from /usr/include/wx-3.0/wx/utils.h:26,
                 from BlockFile.cpp:51:
/usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
make[3]: *** [audacity-BlockFile.o] Error 1
```

isnan() is not defined, but std::isnan() is defined. Thus use
std::isnan() for all C++11 compilers, since isnan() is part of C++11.

### CODE REVIEW

**Comment by vadz** [comment]
This looks correct and I did a similar thing myself back in bfdaa9173ed5b20dd5a9cd83241ce44fc0eff960 for `isfinite()`, but I wonder if we should continue testing for C++11 in yet another place or just do it once. It looks like things could be simpler if we did it in the beginning of the C++ part (and also include `<cmath>` just once there), what do you think?

**Comment by bdrung** [comment]
I thought about that too, but decided to keep the diff small. Combining the C++11 checks will probably look nicer. Feel free to do that.

**Comment by bdrung** [comment]
Done in pull request #283

**Comment by vadz** [comment]
Thanks, I've actually started doing it myself too, but it resulted in exactly the same thing as you submitted anyhow. I'll apply this soon.

**Comment by bdrung** [comment]
Thanks. Can you merge that fix into the branch for 3.0.x?
