### ISSUE TITLE
OpenGL Canvas not redrawn under Wayland

### ISSUE THREAD

**Issue by 0mhu** [wxWidgets/wxWidgets#25848]
#### Bug description:

Unfortunately, I'm not able to provide a very good bug description because I'm not able to track down what exactly the problem is. Sorry about that...

I use KiCAD v9.0.4 and experience the following issue:
https://gitlab.com/kicad/code/kicad/-/issues/21089

Kicad uses a https://docs.wxpython.org/wx.ScrolledCanvas.html#wx-scrolledcanvas ScrolledCanvas (I think) to draw a footprint preview using openGL. This openGL rendering howerver does not work. See this screencast: https://gitlab.com/-/project/15502567/uploads/730f2e99e5548710f830485c835322e6/Screencast_From_2025-06-07_15-03-19.mp4

I traced it in Kicad's code down to the point where I see that the pain evewnt of the widget is called as expected and the openGL calls to draw the surface are executed. However nothing happens unless one of hte two things:

1. The Window is resized
2. Another GUI element like the dropdown of the zoom selection (see video) covers the canvas and somehow triggers a correct redraw.

KiCAD's development team suggested to report the issue to Mutter. However, the issue persists both on Gnome (using Mutter) and KDE which uses a differnt Wayland compositor. Therefore, I guess it's not a compositor problem.

Can you help me track that down? I'm on these bugs for months and can't find support anywhere.
I don't know, if it's wxWidgets, GDK or anything else and can't spot anything obviously wrong in Kicad either.

#### Expected vs observed behaviour:

OpenGL view should be correctly rendered

#### To Reproduce:

Open Kicad under a wayland session and go to the schematic editor -> Assign Footprints -> Select Footprint -> Open Footprint Preview.

### Platform and version information

- wxWidgets version  you use: 3.2.8.1
- wxWidgets port  you use: wxGTK
- OS  and its version: Arch, but happens on Ubuntu as well
  
  + GTK version:  3.24.51
  + Which GDK  backend is used: Wayland
  + Desktop environment : Gnome and KDE
  + Current theme: Theme independent.

**Comment by vadz** [comment]
OpenGL definitely works under Wayland in general, so I suspect this issue is specific to the video card you use. Can you try building wxWidgets 3.3.1 and one of its OpenGL samples, e.g. `samples/opengl/cube`? Does it work correctly for you?

Also, does this issue happen on other machines?

**Comment by 0mhu** [comment]
Thanks for the answer,

The issue persists on all my systems: An AMD Ryzen with iGPU, a Ryzen with dedicated AMD GPU, an Intel 6th generation with iGPU and on all other PCs of my friends.
One of my systems:
````
Platform: Arch Linux, 64 bit, Little endian, wxGTK, Wayland, gnome, wayland
OpenGL: Intel, Mesa Intel(R) HD Graphics 530 (SKL GT2), 4.6 (Compatibility Profile) Mesa 25.1.1-arch1.1
Build Info:
    Date: May 21 2025 09:11:42
    wxWidgets: 3.2.8 (wchar_t,wx containers) GTK+ 3.24
    Boost: 1.88.0
    OCC: 7.8.1
    Curl: 8.13.0
    ngspice: 44.2
    Compiler: GCC 15.1.1 with C++ ABI 1020
````

The problem is: OpenGL in general works. Kicad also uses the same class at different points in the software where it does work. Just this one dialog does not work. I personally don't get it. Under X11 everything works fine. But Arch dropped X for wayland.

**Comment by vadz** [comment]
I am afraid we're going to need some way of reproducing the problem in order to be able to debug and potentially fix it. If it works for the other OpenGL windows but not this one, there must be some salient difference between them, but unfortunately I have no idea what could it be...

**Comment by 0mhu** [comment]
Is there anythign I can debug?
I'm not too much into the whole GUI chain and can't really debug that myself. I was just able to see that the redraw event is actually executing and that the glClear() and subsequent drawing commands etc. execute.

Is there a way to pinpoint it to some component? As I said, this is more or less a desperate try to get support for that because, like all other wayland related issues, I cannot file bug reports because I can't point to specific errors.

I can't understand why they roll out wayland with that many bugs and no way of filing bug reports...

**Comment by RobertRoeb** [comment]
Is only this OpenGl window in a ScrolledCanvas?

**Comment by 0mhu** [comment]
> Is only this OpenGl window in a ScrolledCanvas?

No. It's a generic class `EDA_DRAW_PANEL_GAL` derived from `wxScrolledCanvas`. Kicad seems to use this in some places. See the code here https://gitlab.com/kicad/code/kicad/-/blob/master/common/draw_panel_gal.cpp?ref_type=heads#L67

There is a Repaint function / a Paint callback inside that class
https://gitlab.com/kicad/code/kicad/-/blob/master/common/draw_panel_gal.cpp?ref_type=heads#L194

This get called. I verified that. Subsequently this function executes this line:
https://gitlab.com/kicad/code/kicad/-/blob/master/common/draw_panel_gal.cpp?ref_type=heads#L304

which then leads to the view elements and their opengl drawing commands.
Despite executing this whenever the GUI should render, there is no visible output unless the window is resized or a GUI element which overlays a dropdown over the canvas is activated. 

@vadz  Is there anything I can do? Arch dropping X11 and Ubuntu and other distros following created a huge mess on my side and I need that stuff that's broken for years fixed.

**Comment by vadz** [comment]
Sorry, I just have no idea about what could be causing this and no practical way to debug it. If you can reproduce this by cherry picking parts of KiCad code into cube OpenGL sample until it stops working, I'd at least try to debug it (no guarantee of success, of course), but without this I simply don't know.

**Comment by 0mhu** [comment]
> Sorry, I just have no idea about what could be causing this and no practical way to debug it. If you can reproduce this by cherry picking parts of KiCad code into cube OpenGL sample until it stops working, I'd at least try to debug it (no guarantee of success, of course), but without this I simply don't know.

Thanks @vadz  for your help. I totally understand that you cannot help with that random issue. 
I spent ~20 hours Debugging kicad, wxwidgets, mesa etc. and couldn't find anything that's not really working. There are weird things going on.. If the drawing is updated without the window in focus, it works...
I'm giving up. I still have no clue, if it's 

- Wayland
- GDK
- wxwidgets
- kicad
- mesa
- something else?

 Maybe it's time to go back to windows after 15 years of Linux.

**Comment by dsa-t** [comment]
I wonder if this could be related to https://github.com/wxWidgets/wxWidgets/issues/25496

(Unfortunately I won't be able to help with the repro case for a while)

**Comment by vadz** [comment]
>  If the drawing is updated without the window in focus, it works...

This is a horrible hack, but in this case would giving focus to some other window, calling `Refresh()` and then putting focus back work?

> Maybe it's time to go back to windows after 15 years of Linux.

Can't you just use Xwayland and run KiCad under it? This is not great, but not nearly as bad as going back to Windows...

**Comment by 0mhu** [comment]
> This is a horrible hack, but in this case would giving focus to some other window, calling Refresh() and then putting focus back work?

I will try that...

> Can't you just use Xwayland and run KiCad under it? This is not great, but not nearly as bad as going back to Windows...

This doesn't work either... Once you lose focus on a window, the mouse capture does not work anymore and the cursor in kicad only moves if you click to a position. So changing to another application a single time breaks everything.

**Comment by dsa-t** [comment]
By "use Xwayland" it was meant you run kicad like this:

`GDK_BACKEND=x11 kicad`

**Comment by 0mhu** [comment]
@dsa-t I know. That doesn't work. The schematic editor works  fine as long as it doesn't lose focus. Once I tab to another window and go back to kicad,   the cursor in kicad doesn't work anymore. Zooming with mousewheel is then also impossible. 

At least that works with wayland.

**Comment by dsa-t** [comment]
> Once I tab to another window and go back to kicad, the cursor in kicad doesn't work anymore. Zooming with mousewheel is then also impossible.

That's weird. I don't remember seeing this on my Manjaro+KDE+Wayland+Intel system (that was like months ago)

**Comment by dsa-t** [comment]
Does that also happen with the wxWidgets `pyramid` sample with `GDK_BACKEND=x11`?

**Comment by 0mhu** [comment]
> Does that also happen with the wxWidgets pyramid sample with GDK_BACKEND=x11?

No. Not as far as I can see. But at the moment I'm unable to reproduce this on my machine. Maybe some update fixed that.
However, I have to run
```
GSK_RENDERER=gl GDK_BACKEND=x11 kicad
```
Because with vulkan, the windows do not resize and instead are just padded with a black margin. As far as I found out this is due to my AMD GPU.
Same problem with other applications using wxwidgets, like audacity:

<img width="1916" height="1146" alt="Image" src="https://github.com/user-attachments/assets/9a218c53-0745-4b37-8ee3-c24ca8478a86" />

**Comment by dsa-t** [comment]
`GSK_RENDERER` seems to be a GTK4 variable. wx uses GTK3. I suppose it shouldn't have any effect?

**Comment by 0mhu** [comment]
> GSK_RENDERER seems to be a GTK4 variable. wx uses GTK3. I suppose it shouldn't have any effect?
but it does. If I leave it, the rendering defaults to vulkan and is broken.

**Comment by vadz** [comment]
I just don't understand how is this possible, `GSK_RENDERER` is not used anywhere by GTK3, which uses Cairo. Could it somehow affect the compositor itself (but then you'd probably need to define it when launching it and not when launching the sample)? Which compositor do you use BTW?

**Comment by 0mhu** [comment]
> Which compositor do you use BTW?

I'm using gnome, so mutter as compositor. But I have tried out KDE, which uses something else. Still the same results.

**Comment by 0mhu** [comment]
> OpenGL definitely works under Wayland in general, so I suspect this issue is specific to the video card you use. Can you try building wxWidgets 3.3.1 and one of its OpenGL samples, e.g. `samples/opengl/cube`? Does it work correctly for you?

I found the time to do testing on all opengl examples. Despite trying everything (xwayland, wayland, different PCs), I cannot get it to break. Everything works perfectly in the examples.

**Comment by vadz** [comment]
It should be possible to find the salient difference between what KiCad does and what the samples do, e.g. by grafting KiCad code into the sample and then removing the differences between it and the original code until the problem is fixed. But doing it requires being able to reproduce the problem in the first place and, IIUC, nobody else could do it so far, so the only person who can do it is you...

**Comment by dsa-t** [comment]
May this be related to AUI usage as well? (https://bugs.launchpad.net/ubuntu/+source/gtk4/+bug/2130248)

**Comment by vadz** [comment]
If so, it could be fixed by 2e2e285a8a (Don't do anything in wxGTK wxWindow::Update() under Wayland, 2025-02-26) as wxAUI does plenty of calls to `Update()`. Is it possible to retest KiCad built against 3.3 to see if it still shows this problem?

**Comment by 0mhu** [comment]
> Is it possible to retest KiCad built against 3.3 to see if it still shows this problem?

Last time I tried, i wasn't able to compile Kicad against 3.3. Too many errors. But I will have a look at it. Maybe I can backport this fix to 3.2 and try it out.

**Comment by dsa-t** [comment]
KiCad master builds with wx 3.3 (at least on Windows)

**Comment by 0mhu** [comment]
@dsa-t , I can't get it to build. 

Kicad:
```
ImportError: libwx_gtk3u_core-3.2.so.0: cannot open shared object file: No such file or directory
CMake Error at cmake/FindwxPython.cmake:56 (message):
  wxPython/Phoenix does not appear to be installed on the system
Call Stack (most recent call first):
  CMakeLists.txt:1018 (find_package)


```
wxpython is compiled against wxwidgets v3.2.

If I try to build wxpython against version 3.3, I get a lot of errors like:
```
../../../../sip/cpp/sip_corewxBitmap.cpp:400:15: error: ‘class wxBitmap’ has no member named ‘SetWidth’; did you mean ‘GetWidth’?
  400 |         self->SetWidth(size->x);
      |               ^~~~~~~~
      |               GetWidth
../../../../sip/cpp/sip_corewxBitmap.cpp:401:15: error: ‘class wxBitmap’ has no member named ‘SetHeight’; did you mean ‘GetHeight’?
  401 |         self->SetHeight(size->y);
      |               ^~~~~~~~~
      |               GetHeight
../../../../sip/cpp/sip_corewxBitmap.cpp: In function ‘PyObject* meth_wxBitmap_SetDepth(PyObject*, PyObject*, PyObject*)’:
../../../../sip/cpp/sip_corewxBitmap.cpp:1599:21: error: ‘class wxBitmap’ has no member named ‘SetDepth’; did you mean ‘GetDepth’?
 1599 |             sipCpp->SetDepth(depth);
      |                     ^~~~~~~~
      |                     GetDepth
../../../../sip/cpp/sip_corewxBitmap.cpp: In function ‘PyObject* meth_wxBitmap_SetHeight(PyObject*, PyObject*, PyObject*)’:
../../../../sip/cpp/sip_corewxBitmap.cpp:1639:21: error: ‘class wxBitmap’ has no member named ‘SetHeight’; did you mean ‘GetHeight’?
 1639 |             sipCpp->SetHeight(height);
      |                     ^~~~~~~~~
      |                     GetHeight
../../../../sip/cpp/sip_corewxBitmap.cpp: In function ‘PyObject* meth_wxBitmap_SetWidth(PyObject*, PyObject*, PyObject*)’:
../../../../sip/cpp/sip_corewxBitmap.cpp:1796:21: error: ‘class wxBitmap’ has no member named ‘SetWidth’; did you mean ‘GetWidth’?
 1796 |             sipCpp->SetWidth(width);
      |                     ^~~~~~~~
      |                     GetWidth

```

I don't know, how you do it, but I can't manage to compile it against version 3.3.

**Comment by dsa-t** [comment]
You may have to patch it: https://gitlab.com/kicad/packaging/kicad-vcpkg-registry/-/blob/b31e1a80d213ec39594c96807f86993196d31176/ports/wxpython-33/wx3.3-compat-fixes.patch

**Comment by 0mhu** [comment]
> You may have to patch it: https://gitlab.com/kicad/packaging/kicad-vcpkg-registry/-/blob/b31e1a80d213ec39594c96807f86993196d31176/ports/wxpython-33/wx3.3-compat-fixes.patch

This doesn't work. I can apply the patch. But it does not compile. The patch does not touch any of the broken C++ files.

**Comment by dsa-t** [comment]
It does ignore `SetDepth`, `SetWidth`, `SetHeight`, probably you need to regenerate the cpp classes:

<img width="846" height="501" alt="Image" src="https://github.com/user-attachments/assets/9a6a8eae-b3c4-41d9-b142-e0c14f72233c" />

Also there's https://gitlab.com/kicad/packaging/kicad-vcpkg-registry/-/blob/b31e1a80d213ec39594c96807f86993196d31176/ports/wxpython-33/add-enumclass-support.patch

**Comment by 0mhu** [comment]
@dsa-t , unfortunately, I cannot manage to get this thing to build, even with your patches.

Accoding to the readme  `python build.py dox etg --nodoc sip build` should do the trick.

```
Will build using: "/usr/bin/python"
3.13.7 (main, Aug 15 2025, 12:34:02) [GCC 15.2.1 20250813]
Python's architecture is 64bit
cfg.VERSION: 4.2.3

Running command: dox
Checking for /home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/bin/doxygen-1.9.1-linux...
bash ./regen.sh xml


Finished command: dox (0m9.15s)
Running command: etg
"/usr/bin/python" etg/_stc.py --sip --nodoc
Unable to find xml file for ITEM: wxTextSearch
Tried: /home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/ext/wxWidgets/docs/doxygen/out/xml/classwx_text_search.xml
       /home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/ext/wxWidgets/docs/doxygen/out/xml/structwx_text_search.xml
       /home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/ext/wxWidgets/docs/doxygen/out/xml/wxTextSearch
Traceback (most recent call last):
  File "/home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/etg/_stc.py", line 278, in <module>
    run()
    ~~~^^
  File "/home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/etg/_stc.py", line 158, in run
    mod = textctrl.parseAndTweakModule()
  File "/home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/etg/textctrl.py", line 34, in parseAndTweakModule
    etgtools.parseDoxyXML(module, ITEMS)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/etgtools/__init__.py", line 82, in parseDoxyXML
    raise DoxyXMLError(msg)
etgtools.DoxyXMLError: Unable to find xml file for ITEM: wxTextSearch
Command '"/usr/bin/python" etg/_stc.py --sip --nodoc' failed with exit code 1.
Finished command: etg (0.147s)

```

**Comment by dsa-t** [comment]
You may need to follow closely what [portfile.cmake](https://gitlab.com/kicad/packaging/kicad-vcpkg-registry/-/blob/b31e1a80d213ec39594c96807f86993196d31176/ports/wxpython-33/portfile.cmake) does. 

Also note there's some Windows defines in [CMakeLists.txt](https://gitlab.com/kicad/packaging/kicad-vcpkg-registry/-/blob/b31e1a80d213ec39594c96807f86993196d31176/ports/wxpython-33/CMakeLists.txt)

**Comment by dsa-t** [comment]
(or you may try running vcpkg on Linux too)

**Comment by 0mhu** [comment]
I'm sorry, but I can't get it running:

- https://gitlab.com/kicad/packaging/kicad-vcpkg-registry/-/blob/b31e1a80d213ec39594c96807f86993196d31176/ports/wxpython-33/portfile.cmake#L118
`./build.py dox` works
- ./build.py etg --nodoc sip    does not, because there is no `wxTextSearch` in the produced doxygen output.

**Comment by dsa-t** [comment]
Did you copy wxWidgets sources with ref `v3.3.0` to `ext/wxWidgets/`?

**Comment by 0mhu** [comment]
> Did you copy wxWidgets sources with ref v3.3.0 to ext/wxWidgets/?

I cleaned everything and tried again:
Now I get:
```
Running command: etg
"/usr/bin/python" etg/_xml.py --sip --nodoc
Traceback (most recent call last):
  File "/home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/etg/_xml.py", line 117, in <module>
    run()
    ~~~^^
  File "/home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/etg/_xml.py", line 103, in run
    m = c.find('byte_offset')
  File "/home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/etgtools/extractors.py", line 129, in find
    raise ExtractorError("Unable to find item named '%s' within %s named '%s'" %
                         (head, self.__class__.__name__, self.name))
etgtools.extractors.ExtractorError: Unable to find item named 'byte_offset' within ClassDef named 'wxXmlParseError'
Command '"/usr/bin/python" etg/_xml.py --sip --nodoc' failed with exit code 1.

```

I tried building kicad without wxpython, according to 
> The KICAD_SCRIPTING_WXPYTHON option is used to enable building the wxPython interface into Pcbnew including the wxPython console

But setting -DKICAD_SCRIPTING_WXPYTHON=0 crashes the build.

**Comment by dsa-t** [comment]
`byte_offset` was indeed present in `v3.3.0` interface header: https://github.com/wxWidgets/wxWidgets/blob/v3.3.0/interface/wx/xml/xml.h#L571

You may need to remove the related lines: 

<img width="502" height="247" alt="Image" src="https://github.com/user-attachments/assets/ee731a45-3f8a-42b9-ada0-9f7d4622241c" />

also see: https://github.com/wxWidgets/wxWidgets/issues/25531

**Comment by 0mhu** [comment]
> You may need to remove the related lines:
I did.

The next thing is 
```
Unable to find xml file for ITEM: wxVScrolledWindow
Tried: /home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/ext/wxWidgets/docs/doxygen/out/xml/classwx_v_scrolled_window.xml
       /home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/ext/wxWidgets/docs/doxygen/out/xml/structwx_v_scrolled_window.xml
       /home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/ext/wxWidgets/docs/doxygen/out/xml/wxVScrolledWindow

```
I will rebuilt wxwidgets with `3.3.0`. I'm currently on `3.3.1`. Maybe that gets rid of most of that stuff.

**Comment by dsa-t** [comment]
> wxVScrolledWindow

may need to patch these up: https://github.com/wxWidgets/Phoenix/blob/fedec8e16c85417ff2beb6c2fc7cf5ef4a2d407e/etg/vscroll.py#L25

**Comment by 0mhu** [comment]
I managed to get a lot further. But there are still errors in the generated sip files:
```
Running command: sip
sip-build --no-compile
These bindings will be built: _core.
Generating the _core bindings...
sip-build: /home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/sip/gen/geometry.sip: line 373: column 5: 'wxRect2DDouble::Inflate' has overloaded functions with the same Python signature
/home/mhu/projects/ext/python-wxpython/src/wxPython-4.2.3/sip/gen/geometry.sip: line 399: column 5: 'wxRect2DDouble::Deflate' has overloaded functions with the same Python signature
Command 'sip-build --no-compile' failed with exit code 1.
Finished command: sip (0m4.914s)
./build.py etg --nodoc sip  28.02s user 3.42s system 99% cpu 31.550 total

```

**Comment by vadz** [comment]
Sorry to butt in but maybe it would be easier for you to just patch wx 3.2 you were using before: the [commit in question](https://github.com/wxWidgets/wxWidgets/commit/2e2e285a8a039960d532088ecf2c0da392b3aab9) just makes `Update()` do nothing when using Wayland, so should be trivially backportable (you may just comment/ifdef out the entire body of this function to make it always do nothing).

**Comment by 0mhu** [comment]
> Sorry to butt in but maybe it would be easier for you to just patch wx 3.2

Yeah. Makes sense... I've manually patched the sip file and give it a last try. If that doesn't work, I will patch v3.2

@dsa-t , I''m giving up: 
```
../../../../sip/cpp/sip_corewxWindow.cpp: In function ‘PyObject* meth_wxWindow_MSWDisableComposited(PyObject*, PyObject*)’:
../../../../sip/cpp/sip_corewxWindow.cpp:12224:21: error: ‘class wxWindow’ has no member named ‘MSWDisableComposited’
12224 |             sipCpp->MSWDisableComposited();
      |                     ^~~~~~~~~~~~~~~~~~~~

```
The CPP files have been regenerated, but still don't compile.

**Comment by 0mhu** [comment]
>Sorry to butt in but maybe it would be easier for you to just patch wx 3.2 you were using before: the [commit in question](https://github.com/wxWidgets/wxWidgets/commit/2e2e285a8a039960d532088ecf2c0da392b3aab9) just makes Update() do nothing when using Wayland, so should be trivially backportable (you may just comment/ifdef out the entire body of this function to make it always do nothing).

I cherry-picked the commit.
On the first run of Kicad, the broken window was rapidly taking focus all the time and glitching with the other windows. However, I cannot reproduce that anymore... Now, it simply behaves the same way it did before. The opengl context does not render until the window is resized, or a dropdown overlays the gl Area.

**Comment by 0mhu** [comment]
I was able to recreate the focus issues. See below youtube video. I'm not switching the focus manually.

https://www.youtube.com/watch?v=NDCtmQgbixk

**Comment by 0mhu** [comment]
Do you have any idea, why the [commit](https://github.com/wxWidgets/wxWidgets/commit/2e2e285a8a039960d532088ecf2c0da392b3aab9) makes things much worse?
If that makes it into the release, Kicad will be fully broken for me.

**Comment by dsa-t** [comment]
I'm not sure which system component is responsible for this issue, but perhaps you can file a bug report to https://gitlab.gnome.org/GNOME/gtk/-/issues

**Comment by vadz** [comment]
> Do you have any idea, why the [commit](https://github.com/wxWidgets/wxWidgets/commit/2e2e285a8a039960d532088ecf2c0da392b3aab9) makes things much worse?

No, sorry, I simply can't explain _anything_ in this issue, it's a complete mystery. I strongly suspect there must be something particular to your system, but I have no idea what could it be.

>  If that makes it into the release, Kicad will be fully broken for me.

In particular, I still have no idea why it's broken even when using X(Wayland) for you, this is probably a separate issue, but I still could never reproduce it.

**Comment by dsa-t** [comment]
You might also try to build older versions of various system components to see if there was a regression.

**Comment by 0mhu** [comment]
> I'm not sure which system component is responsible for this issue, but perhaps you can file a bug report to https://gitlab.gnome.org/GNOME/gtk/-/issues

I don't think this will help. I was told by Gnome before that they don't care and they told me I should use other software.
In fact, they send me here (to wxwidgets) and told me that this is the problem.
> No, sorry, I simply can't explain anything in this issue, it's a complete mystery. I strongly suspect there must be something particular to your system, but I have no idea what could it be.

Not really. I can reproduce this on all machines with different linux distributions. My friends have these problems as well.

**Comment by dsa-t** [comment]
> I was told by Gnome before that they don't care and they told me I should use other software.

I guess we could switch KiCad to wxQt eventually: https://gitlab.com/kicad/code/kicad/-/merge_requests/1953

**Comment by vadz** [comment]
Which version(s) of Ubuntu can you reproduce these problems under? I have a number of them here, so I could try building KiCad and testing it myself, although it's not going to be simple for me (as I had never built it before).

**Comment by 0mhu** [comment]
Just use the latest version (this ensures the desktop runs on wayland).
If you're fine with it, you can use kicad's ppa: https://www.kicad.org/download/details/ubuntu/

So no need to build it, to see if the issue is there. I'm currently installing a Ubuntu 25.10 VM as well, just to be 100% safe.

**Comment by vadz** [comment]
OK, I've installed KiCad under Ubuntu 25.10 VM. I don't see anything wrong just clicking around, could you please give me the exact instructions for reproducing the problem? Please keep in mind that I'm completely unfamiliar with KiCad as a user, i.e. when you say "Open footprint assignment tool" it's not really clear for me, is it the same as "Footprint editor" (which is one of the choices on the welcome screen) or not? I.e. please tell me which menu to open and which command to choose from it on a new KiCad installation. TIA!

**Comment by dsa-t** [comment]
> I don't think this will help. I was told by Gnome before that they don't care and they told me I should use other software.
> In fact, they send me here (to wxwidgets) and told me that this is the problem.

Maybe the devs at the bugtracker will help us identify the issue. The common components here appear to be _gtk_ and _mesa_.

> I can reproduce this on all machines with different linux distributions. My friends have these problems as well.

This sounds serious.

---

Does it also reproduce if KiCad is built with `KICAD_ENABLE_EGL=1` and wxWidgets with `wxUSE_GLCANVAS_EGL=ON`? (should be the default on Arch)

**Comment by vadz** [comment]
> > I can reproduce this on all machines with different linux distributions. My friends have these problems as well.
> 
> This sounds serious.

I still can't reproduce this under Ubuntu 25.10.

**Comment by 0mhu** [comment]
Thanks for all your time so far. I will try out the things @dsa-t  suggested and do some trials with different OSs to see where the problem is.

Indeed I cannot reproduce it with ubuntu in a vm either.
I will probably find some time during the upcoming weekend.

**Comment by jaskij** [comment]
I can reliably reproduce refresh issues in KiCad's schematic editor (eeschema) under Wayland, using either KDE/KWin or GNOME/Mutter. KDE on X11 works just fine. What may be of note is that the issue is *only* in the schematic editor - PCB editor works just fine. Haven't tried footprint or symbol editor.

@vadz ~~untested, but what should~~ to reproduce the issue:

- On the welcome screen pick File -> Open demo project
- The specific project shouldn't matter - I used `complex_hierarchy/complex_hierarchy.pro`
- Once the project is open, double click the schematic file, `complex_hierarchy.kicad_sch`
- In the main area scroll your mouse wheel - it should zoom

---

The OS is Arch/CachyOS (it was originally Manjaro, migrated to Arch, now using CachyOS repos). It's a dual-monitor setup (Philips 325E1), using GeForce 1650. GPU drivers are using open kernel modules and proprietary userspace.

KiCad's diagnostic information:

```
Application: KiCad x86_64 on x86_64

Version: 9.0.6, release build

Libraries:
	wxWidgets 3.2.9
	FreeType 2.14.1
	HarfBuzz 12.2.0
	FontConfig 2.17.1
	libcurl/8.17.0 OpenSSL/3.6.0 zlib/1.3.1.zlib-ng brotli/1.1.0 zstd/1.5.7 libidn2/2.3.8 libpsl/0.21.5 libssh2/1.11.1 nghttp2/1.68.0 nghttp3/1.13.1 mit-krb5/1.21.3

Platform: Arch Linux, 64 bit, Little endian, wxGTK, X11, KDE, x11

Build Info:
	Date: Dec  9 2025 17:18:52
	wxWidgets: 3.2.9 (wchar_t,wx containers) GTK+ 3.24
	Boost: 1.89.0
	OCC: 7.9.3
	Curl: 8.17.0
	ngspice: 45
	Compiler: GCC 15.2.1 with C++ ABI 1020

Build settings:
	KICAD_USE_EGL=ON
	KICAD_IPC_API=ON

Locale: 
	Lang: en_US
	Enc: UTF-8
	Num: 1 234,5
	Encoded кΩ丈: D0BACEA9E4B888 (sys), D0BACEA9E4B888 (utf8)
```

**Comment by vadz** [comment]
So, just like #26024, this can be only reproduced with multiple monitors? But, unlike there, you can also reproduce it with Kwin and not only Mutter?

**Comment by jaskij** [comment]
> So, just like https://github.com/wxWidgets/wxWidgets/issues/26024, this can be only reproduced with multiple monitors? But, unlike there, you can also reproduce it with Kwin and not only Mutter?

Seems so. Thing is - I tried software disabling my second monitor on *this* setup, and the issue persisted. Maybe physically disconnecting it will stop it?

The issue *does not* happen on my home setup, which is also CachyOS, using a single monitor and a 5070 Ti, a very similar setup.

**Comment by dsa-t** [comment]
> Platform: Arch Linux, 64 bit, Little endian, wxGTK, X11, KDE, x11

Well on Wayland with Wayland backend it should say something like

`Platform: Arch Linux, 64 bit, Little endian, wxGTK, Wayland, KDE, wayland`

and on Wayland with X11 GDK backend (via xwayland), something like:

`Platform: Arch Linux, 64 bit, Little endian, wxGTK, X11, KDE, wayland`

**Comment by vadz** [comment]
But you're sure that you see the issue with Kwin? This is important because it means that either this is a different issue from #26024 (which seems surprising, but possible, I guess) or that issue is not Mutter-specific.

**Comment by jaskij** [comment]
> Well on Wayland with Wayland backend it should say something like

Ah, right, sorry, I was logged into KDE X11 when posting that comment. Correct diagnostic info below.

> But you're sure that you see the issue with Kwin? This is important because it means that either this is a different issue from [#26024](https://github.com/wxWidgets/wxWidgets/issues/26024) (which seems surprising, but possible, I guess) or that issue is not Mutter-specific.

Yes, both GNOME and Plasma, and even with only a single monitor. 

---

What I'd focus on is what is different between eeschema (schematic editor) and pcbnew (PCB editor), since the error is only present in one of them - the other works just fine.

---

```
Application: KiCad x86_64 on x86_64

Version: 9.0.6, release build

Libraries:
	wxWidgets 3.2.9
	FreeType 2.14.1
	HarfBuzz 12.2.0
	FontConfig 2.17.1
	libcurl/8.17.0 OpenSSL/3.6.0 zlib/1.3.1.zlib-ng brotli/1.1.0 zstd/1.5.7 libidn2/2.3.8 libpsl/0.21.5 libssh2/1.11.1 nghttp2/1.68.0 nghttp3/1.13.1 mit-krb5/1.21.3

Platform: Arch Linux, 64 bit, Little endian, wxGTK, Wayland, KDE, wayland

Build Info:
	Date: Dec  9 2025 17:18:52
	wxWidgets: 3.2.9 (wchar_t,wx containers) GTK+ 3.24
	Boost: 1.89.0
	OCC: 7.9.3
	Curl: 8.17.0
	ngspice: 45
	Compiler: GCC 15.2.1 with C++ ABI 1020

Build settings:
	KICAD_USE_EGL=ON
	KICAD_IPC_API=ON

Locale: 
	Lang: en_US
	Enc: UTF-8
	Num: 1 234,5
	Encoded кΩ丈: D0BACEA9E4B888 (sys), D0BACEA9E4B888 (utf8)
```

**Comment by jaskij** [comment]
Dropped eglinfo and glewinfo into a gist: https://gist.github.com/jaskij/84898ab99081ab131ca8b938f0cf8e75

If I can help with any more diagnostic info or anything, do tell.

**Comment by 0mhu** [comment]
> What I'd focus on is what is different between eeschema (schematic editor) and pcbnew (PCB editor), since the error is only present in one of them - the other works just fine.

This is very weird. eeschema and pcbnew work fine for me. Just the footprint assignment tool is broken. 


> Does it also reproduce if KiCad is built with `KICAD_ENABLE_EGL=1` and wxWidgets with `wxUSE_GLCANVAS_EGL=ON`? (should be the default on Arch)

`KICAD_ENABLE_EGL=1` is set by default in Arch's package. 
Executing `wxUSE_GLCANVAS_EGL=ON kicad` does not change the behavior.

**Comment by jaskij** [comment]
> This is very weird. eeschema and pcbnew work fine for me. Just the footprint assignment tool is broken.

For me eeschema only refresh when the window gains focus. Not if it's focused, not if it's unfocused (cross-inspection), only when it gains focus (and maybe when it loses, don't remember).

**Comment by jaskij** [comment]
Just tested: symbol editor is also broken, while footprint editor works fine. To sum up how it affects me:

- schematic and symbol editor broken
- PCB and footprint editor work

**Comment by 0mhu** [comment]
> For me eeschema only refresh when the window gains focus. Not if it's focused, not if it's unfocused (cross-inspection), only when it gains focus (and maybe when it loses, don't remember).
Just to see if it's the same general thing as for me with the assignment tool: Does your window render, if you resize it?

It's completely strange that this stuff only happens in certain windows... The Widget and base class used by Kicad is the exact same for all of these openGL windows.

**Comment by pvantrap** [comment]
Chipping in here from #26024 after seeing the cross-link; with a multi-monitor setup using Wayland on KDE (KWin) from Ubuntu 2025.10, I can't reproduce the Footprint Editor rendering issues you have @0mhu . Will try later on with Mutter.

**Comment by ptome** [comment]
Hello. Here's a simple reproducer. I found this issue because of the Erlang bindings.

I can reproduce on my system:

- Fedora 43 (KDE Plasma, Wayland)
- RTX 4070 Super (Fusion drivers)
- Dual-monitor
- wxGTK3 3.2.8

Compile with: ``g++ -o simpledraw simpledraw.cpp `wx-config --cxxflags --libs` ``

Running with `GDK_BACKEND=x11 ./simpledraw` I can draw on the panel and it also updates correctly when resizing the window.

Running with `./simpledraw` the drawing doesn't work, but it updates when resizing the window.

[simpledraw.cpp](https://github.com/user-attachments/files/25532869/simpledraw.cpp)

**Comment by vadz** [comment]
@ptome Sorry, this has nothing to do with this issue, your code doesn't even use `wxGLCanvas`. What you see is explained by the (hopefully) prominent note in [wxClientDC documentation](https://docs.wxwidgets.org/3.2/classwx_client_d_c.html).
