### PR TITLE
Fix ANSI build on GCC older than 4.6

### PR DESCRIPTION
**Pull request by lanurmi**
GCC 4 is supported, and ANSI build is "supported", so have both work together.

Compilation error detected with GCC 4.4.7 on CentOS 6.

I don't use ANSI build myself, I just sometimes compile it out of curiosity. IIRC, not too long ago, the ANSI build was broken on master for more than a year and nobody noticed or cared.

### CODE REVIEW

**Comment by vadz** [comment]
Could you please explain what the actual error is? The comment speaks about warnings, but I have no idea what are they and why do we only get them in ANSI build.

Also, gcc docs say:

> For strftime formats, the third parameter is required to be zero.

so perhaps we just need to replace `4` with `0` here? I have really no idea where does this `4` come from...

**Comment by lanurmi** [comment]
> Could you please explain what the actual error is? The comment speaks about warnings, but I have no idea what are they

Sure; should've done that in the first place. I've amended the commit message to include the actual error, too.

The error is `include/wx/wxcrt.h:1057: error: format string argument not a string type`, and it is triggered by all files that `#include`  wxcrt.h, even if there aren't any calls to `wxStrftime()`.

This is, presumably, the kind of warning/error that the `wxGCC_ONLY_WARNING_SUPPRESS` call a few lines later is trying to suppress. (Or why is the suppression call there at all, if there's nothing to suppress?) But on old GCCs the suppression macro doesn't do anything, as documented.

Now that I investigated further, this whole issue isn't even specific to very old GCCs, but also to newer ones (tested GCC 8.3.1 on F29). And my fix doesn't even fix it for GCC >= 4.6, it seems. The attempt to suppress isn't successful, and there is always an error.

> and why do we only get them in ANSI build.

That's because `WX_ATTRIBUTE_FORMAT` [only does anything in ANSI build](https://github.com/wxWidgets/wxWidgets/blob/master/include/wx/defs.h#L542).

> > For strftime formats, the third parameter is required to be zero.
> 
> so perhaps we just need to replace `4` with `0` here? I have really no idea where does this `4` come from...

Replacing with `0` doesn't seem to change anything, unfortunately. It could still be the right thing to do, though.

**Comment by vadz** [comment]
Oops, yes, seeing the error message I realize that 36c5884acb couldn't actually work -- `format` attribute can only apply to `char*`, not `wxString`. So I'll simply remove it for now.

It might be worth adding an overload taking `const char* format` just to be able to check this. After all, the format will, most of the time, be just a simple string literal.

**Comment by lanurmi** [comment]
> It might be worth adding an overload taking `const char* format` just to be able to check this. After all, the format will, most of the time, be just a simple string literal.

The remaining question is, should the `WX_ATTRIBUTE_FORMAT` macro really be defined as a no-op for Unicode builds, as it currently is defined? Virtually nobody will ever have these checks enabled in that case.

**Comment by vadz** [comment]
The only alternative would be to use the macro only on overloads taking `const char*` and this doesn't seem simple. And what else can we do?
