### ISSUE TITLE
wxWidgets-3.3.0.0 compiles well enough, though compiling Code::Blocks gainst it fails

### ISSUE THREAD

**Issue by JaiSoone** [wxWidgets/wxWidgets#25177]
The error is: no matching function for call to 'wxUnderscoreWrapper(wxString&)'

The actual compile step is:

g++.exe -Wall -std=gnu++11 -m64 -O3 -pipe -mthreads -fmessage-length=0 -fexceptions -Winvalid-pch -DHAVE_W32API_H -D__WXMSW__ -DWXUSINGDLL -DcbDEBUG -DCB_PRECOMP -DwxUSE_UNICODE -D_WIN64 -Woverloaded-virtual -DEXPORT_LIB -DEXPORT_EVENTS -DWXMAKINGDLL_SCI -std=gnu++11 -m64 -Wno-unused-local-typedefs -Wno-deprecated-declarations -march=native -freport-bug -fno-omit-frame-pointer -IC:\msys64\home\NateJoe\wxWidgets\local\wxWidgets-3.3.0.0\include -IC:\msys64\home\NateJoe\wxWidgets\local\wxWidgets-3.3.0.0\lib\gcc_dll\mswu -Isdk\wxscintilla\include -Iinclude\tinyxml -Iinclude -Iinclude\tinyxml -Iinclude\scripting\include -Isdk\mozilla_chardet\include -Isdk\mozilla_chardet\include\mfbt -Isdk\mozilla_chardet\include\nsprpub\pr\include -Isdk\mozilla_chardet\include\xpcom -Isdk\mozilla_chardet\include\xpcom\base -Isdk\mozilla_chardet\include\xpcom\glue -Isdk\scripting\bindings -IC:\msys64\ucrt64\include -c C:\msys64\home\NateJoe\CodeBlocks\replcement_regex\final\wxWidgets330Changes\codeblocks-code-r13611-trunk\src\sdk\projectfileoptionsdlg.cpp -o .objs32_64\sdk\projectfileoptionsdlg.o
In file included from C:\msys64\home\NateJoe\wxWidgets\local\wxWidgets-3.3.0.0\include/wx/intl.h:18,
from C:\msys64\home\NateJoe\wxWidgets\local\wxWidgets-3.3.0.0\include/wx/window.h:27,
from C:\msys64\home\NateJoe\wxWidgets\local\wxWidgets-3.3.0.0\include/wx/msw/private.h:20,
from C:\msys64\home\NateJoe\wxWidgets\local\wxWidgets-3.3.0.0\include/wx/wxprec.h:28,
from include/sdk_common.h:24,
from include/sdk_precomp.h:13,
from C:\msys64\home\NateJoe\CodeBlocks\replcement_regex\final\wxWidgets330Changes\codeblocks-code-r13611-trunk\src\sdk\pluginmanager.cpp:10:
C:\msys64\home\NateJoe\CodeBlocks\replcement_regex\final\wxWidgets330Changes\codeblocks-code-r13611-trunk\src\sdk\pluginmanager.cpp: In function 'wxString RemoveCRAndTranslate(const wxString&)':
C:\msys64\home\NateJoe\wxWidgets\local\wxWidgets-3.3.0.0\include/wx/translation.h:48:67: error: no matching function for call to 'wxUnderscoreWrapper(wxString&)'

**Comment by MaartenBent** [comment]
Simple to reproduce with:
```c++
wxString test("hello");
wxString translated = _(test);
```

This seems to be caused by #24957 and is intentional.
You can define [wxNO_REQUIRE_LITERAL_MSGIDS ](https://docs.wxwidgets.org/latest/page_cppconst.html#:~:text=wxNO_REQUIRE_LITERAL_MSGIDS)before including the wx headers as a workaround.
