### ISSUE TITLE
Compatibility problems porint wxPerl

### ISSUE THREAD

**Issue by sciurius** [wxWidgets/wxWidgets#25639]
### Description

This is an on-going report of compatibility issues found when porting wxPerl to wxWidgets 3.3.

#### Introduction

wxPerl is the native Perl interface to wxWidgets. It is an old piece of software and barely maintained for the last 10+ years. Some changes gave been made to have it compile with wxWidgets 3.0 and 3.2 but it depends heavily on 2/x compatibility.

The port is done on an up-to-date Fedora 42 with 3.2 as distributed, and custom built 3.3. The custom builds are done with the Fedora rpm/mock toolset, making sure that the 3.3 builds correspond to the 3.2 builds.

#### Phase 1

As a first step, I built wxPerl with standard wxWidgets 3.2. This has been made to work earlier.

The next step was to eliminate all deprecation warnings. The code now builds clean of these warnings.

#### Phase 2

I installed a custom built wxWidgets 3.3.0, with PR 25632 and 3.0 compatibility enabled.

The following changes were needed to have the build suceed.

wxPGVFBFlags values were used as an int, but now needed to be changed to a `enum wxPGVFBFlags`.

`wxStyledTextCtrl::AddSelection` return type was `int`, needed to be changed to `void`.

A number of wxSTC constants have been removed:

````
wxSTC_CSS_MEDIA
wxSTC_VISUALPROLOG_CHARACTER
wxSTC_VISUALPROLOG_CHARACTER_TOO_MANY
wxSTC_VISUALPROLOG_CHARACTER_ESCAPE_ERROR
wxSTC_VISUALPROLOG_STRING_EOL_OPEN
wxSTC_VISUALPROLOG_STRING_VERBATIM
wxSTC_VISUALPROLOG_STRING_VERBATIM_SPECIAL
wxSTC_VISUALPROLOG_STRING_VERBATIM_EOL
````

(maybe more).

`wxControl::Ellipsize` is documented to have a `wxDC` argument but the compiler insisted on a `wxReadOnlyDC` instead.

According to the wxPerl git history, `wxVariant::GetList` required a return type of `wxList&` up to 2.9.0, then `wxVariantList&` and now the compiler insists on `wxList&` again.

With the above changes, wxPerl can be built with wxWidgets 3.3.0 with 3.0 compatibility mode.

#### Next steps

Eliminate the deprecation warnings.

Try building with wxWidgets 3.3.0 without 3.0 compatibility mode.

**Comment by vadz** [comment]
> I installed a custom built wxWidgets 3.3.0, with PR 25632 and 3.0 compatibility enabled.
> 
> The following changes were needed to have the build suceed.
> 
> wxPGVFBFlags values were used as an int, but now needed to be changed to a `enum wxPGVFBFlags`.

I suspect we may need to rename the existing `wxPGVFBFlags` to something else and turn `wxPGVFBFlags` back to `unsigned char` (as it was in 3.2) again.

Could you please show some examples of what was the exact problem due to the use of `wxPGVFBFlags`?

> `wxStyledTextCtrl::AddSelection` return type was `int`, needed to be changed to `void`.

This should have been at least documented :-( I don't know what it returned before and whether it was useful, but maybe we should make it always return 0 or something. @MaartenBent Do you remember more about this change by chance?

> A number of wxSTC constants have been removed:
> 
> ```
> wxSTC_CSS_MEDIA
> wxSTC_VISUALPROLOG_CHARACTER
> wxSTC_VISUALPROLOG_CHARACTER_TOO_MANY
> wxSTC_VISUALPROLOG_CHARACTER_ESCAPE_ERROR
> wxSTC_VISUALPROLOG_STRING_EOL_OPEN
> wxSTC_VISUALPROLOG_STRING_VERBATIM
> wxSTC_VISUALPROLOG_STRING_VERBATIM_SPECIAL
> wxSTC_VISUALPROLOG_STRING_VERBATIM_EOL
> ```

I think those are just due to the change of Scintilla version. I don't think we can realistically do anything about them.
 
> `wxControl::Ellipsize` is documented to have a `wxDC` argument but the compiler insisted on a `wxReadOnlyDC` instead.

Fixed, thanks.
 
> According to the wxPerl git history, `wxVariant::GetList` required a return type of `wxList&` up to 2.9.0, then `wxVariantList&` and now the compiler insists on `wxList&` again.

It still returns `wxVariantList`, so this is probably due to the change of `wxUSE_STL` from 0 to 1 by default. Again, having some example errors could help with diagnosing this.

**Comment by MaartenBent** [comment]
> This should have been at least documented :-( I don't know what it returned before and whether it was useful, but maybe we should make it always return 0 or something. @MaartenBent Do you remember more about this change by chance?

Just like the removed/renamed `wxSTC_` constants, this function is also generated from `Scintilla.iface`. 
There is no reason in the commit message why it was removed, but it probably didn't return anything and the interface was just wrong: https://github.com/wxWidgets/scintilla/commit/3459e08eb62b867eb7c6a681efacd78281210cfe

I prefer documenting this change, instead of modifying the scintilla sources.

**Comment by vadz** [comment]
> I prefer documenting this change, instead of modifying the scintilla sources.

OK, I'll do this, thanks.

**Comment by vadz** [comment]
Looking further at wxPG compatibility, I think I'm going to do the following to complete/replace the changes of #25562:

- Restore definitions of all enums and `wxPGVFBFlags` as they were in 3.2.
- Rename new enums to different names when they clash with them. Luckily, most of them do not, as they all use `wxPGCamelCase` conversion and old enums mostly used `wxPG_UPPER_CASE` one. But at least `wxPGVFBFlags` and `wxPGPropertyFlags` do clash with the old names, so they will need to be changed.

The trouble is that coming with the good names is really complicated, especially for the latter. I wonder if we could rename _all_ `wxPGFooFlags` to `wxPGFooFlag` instead? Writing `wxPGFooFlag::Value' is not bad, but the difference between `wxPGFooFlag` and `wxPGFooFlags` is tiny but significant. But I just don't have any better ideas. Help?

**Comment by sciurius** [comment]
As for `wxPGVFBFlags`, there are glue routines in wxPerl that call `wxPGCell::GetFailureBehavior` and `PropertyGridEvent::GetValidationFailureBehavior`. The glue routine expected them to return a `wxByte`. It was trivial to change these to `wxPGVFBFlags` since at routine return they are cast to int anyway.

**Comment by sciurius** [comment]
As for `wxVariant::GetList`, this is the code as generated by the Perl interface builder:
````
XS_EUPXS(XS_Wx__Variant_GetList)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "THIS");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	wxVariant *    THIS = (wxVariant *) wxPli_sv_2_object( aTHX_ ST(0), "Wx::Variant" )
;
#if WXPERL_W_VERSION_GE( 2, 9, 0 )
    const wxVariantList& lst = THIS->GetList();
#else
    const wxList& lst = THIS->GetList();
#endif
    PUTBACK;
    wxPli_objlist_push( aTHX_ lst );
    SPAGAIN;
    for( int i = lst.GetCount() - 0; i >= 0; --i )
        wxPli_object_set_deleteable( aTHX_ SP[-i], false );
	PUTBACK;
	return;
    }
}
````

`wxPli_objlist_push` takes a `const wxList&` as second argument, and that went well even when the actual argument was a `const wxVariantList&`. With 3.3.0 it fails to compile:
````
Wx.c: In function ‘void XS_Wx__Variant_GetList(PerlInterpreter*, CV*)’:
Wx.c:20598:31: error: invalid initialization of reference of type ‘const wxList&’ from expression of type ‘const wxVariantList’
20598 |     wxPli_objlist_push( aTHX_ lst );
      |                               ^~~
cpp/helpers.cpp:739:46: note: in passing argument 2 of ‘void wxPli_objlist_push(PerlInterpreter*, const wxList&)’
  739 | void wxPli_objlist_push( pTHX_ const wxList& objs )
      |                                ~~~~~~~~~~~~~~^~~~
````

**Comment by vadz** [comment]
> As for `wxPGVFBFlags`, there are glue routines in wxPerl that call `wxPGCell::GetFailureBehavior` and `PropertyGridEvent::GetValidationFailureBehavior`. The glue routine expected them to return a `wxByte`. It was trivial to change these to `wxPGVFBFlags` since at routine return they are cast to int anyway.

You probably should postpone changing this code until I complete my changes/we release 3.3.1.

**Comment by vadz** [comment]
Could you please retest with the updated #25632? I think I've done what I could to restore as much compatibility as reasonably possible, but please let me know if I missed anything. TIA!

**Comment by sciurius** [comment]
> Could you please retest with the updated [#25632](https://github.com/wxWidgets/wxWidgets/pull/25632)? 

I needed to change every occurrence of `wxPGPropertyFlags` to `wxPGFlags`,

**Comment by vadz** [comment]
> > Could you please retest with the updated [#25632](https://github.com/wxWidgets/wxWidgets/pull/25632)?
> 
> I needed to change every occurrence of `wxPGPropertyFlags` to `wxPGFlags`,

Sorry, why? The intention was to allow the code to keep using `wxPGPropertyFlags` as before (provided 3.2 compatibility is on). Why didn't this work for you?

**Comment by sciurius** [comment]
Maybe another compatibility is needed?

````
PropertyGrid.c: In function ‘void XS_Wx__PGProperty_SetFlagRecursively(PerlInterpreter*, CV*)’:
PropertyGrid.c:20780:33: error: cannot convert ‘wxPGPropertyFlags’ to ‘wxPGFlags’
20780 |       THIS->SetFlagRecursively( flag, set );
      |                                 ^~~~
      |                                 |
      |                                 wxPGPropertyFlags
/usr/include/wx-3.3/wx/propgrid/property.h:1860:40: note: initializing argument 1 of ‘void wxPGProperty::SetFlagRecursively(wxPGFlags, bool)’
 1860 |     void SetFlagRecursively( wxPGFlags flag, bool set );
      |                              ~~~~~~~~~~^~~~
````

**Comment by vadz** [comment]
Yes, compatibility overload for `SetFlagRecursively()` was missing too. I've added it now to the PR, is/was there anything else?

**Comment by sciurius** [comment]
wxPerl now builds with 3.3.0 + updated PR 25632 and 3.0 compatibility enabled.

Great! Thanks a lot.

BTW: wxPerl is on GitHub, if you like: https://github.com/sciurius/wxPerl. You'll need a decent Perl plus some easily installable modules.

**Comment by vadz** [comment]
Excellent, thanks for testing! I'll merge this soon and it will be part of 3.3.1.

It would be really great if we could have done this before 3.3.0, I wonder if there is some way to ask for testing of (at least the reasonably up-to-date) language bindings (wxPython, wxPerl, wxRuby, wxLua, wxErlang and maybe more?) before making the release — preferably without me having to test all of them myself.

**Comment by sciurius** [comment]
Testing the language bindings would be hard, but a completing build is already a good indicator. More precisely, a failing build is a bad indicator :).

I have a [GitHub Action](https://github.com/sciurius/wxPerl/blob/master/.github/workflows/linux.yml) to run after each commit, just like you. I use the distributed wxWidgets but I imagine that you could run the steps after the wxWidgets build.

I would look forward to hamonising our developments a bit.

**Comment by vadz** [comment]
The problem is that this workflow uses the packaged/released wx version while I'd like to run it against the current wx master. Could you add a workflow parameter allowing to specify the hash of wx repository to check out and build perhaps?

**Comment by sciurius** [comment]
I'm not sure I completely understand the hash thing...

I tried to checkout wxWidgets from git but no success so far. See 
https://github.com/sciurius/wxPerl/blob/wxdev/.github/workflows/wxdev.yml

BTW: On newer Debian systems `libwebkit2gtk-4.1-dev` is required, `libwebkit2gtk-4.0-dev` no longer exists.

**Comment by MaartenBent** [comment]
It fails on missing headers from the scintilla/lexilla submodules. Easiest is probably to clone with submodules:

```git clone --recurse-submodules https://github.com/wxWidgets/wxWidgets.git```

and then you can get rid of the `git submodule update --init [path]`.

**Comment by sciurius** [comment]
Thanks.

BTW: On newer Fedora, gstreamer is `gstreamer1-plugins-base-devel` (not 1.0).

**Comment by sciurius** [comment]
@vadz @MaartenBent I can confirm that the current git version of wxPerl (3.006 to be) correctly builds and works with the current git version (3.3.1 to be) of wxWidgets. Compatibility for 3.0 and 3.2 must be enabled.

Great job!

**Comment by sciurius** [comment]
While eliminating the deprecations, I stumbled on the following.

Current code (wxPGProperty):
````
int flags = wxPG_SETVAL_REFRESH_EDITOR;
RETVAL = THIS->SetValueFromString( text, flags );
````

The `flags` argument of `wxPGProperty::SetValueFromString` is now `wxPGPropValFormatFlags`, but this enum has no equivalen for `wxPG_SETVAL_REFRESH_EDITOR`. There is, however, `wxPGSetValueFlags::RefreshEditor`.

How to fix?

**Comment by vadz** [comment]
The old code was buggy — this is exactly the kind of bugs all these changes were supposed to catch, so it's good to see that they were not for nothing.

You couldn't pass `wxPG_SETVAL_REFRESH_EDITOR` to `SetValueFromString()` even before, but it compiled (and I have no idea what it did), it could only be passed to `SetValue()`. If you need to refresh the editor, the equivalent code would be something like this

```cpp
    wxVariant variant(THIS->GetValueRef());
    RETVAL = THIS->StringToValue(variant, text);
    if ( RETVAL )
        SetValue(variant, wxPGSetValueFlags::RefreshEditor);
```

**Comment by sciurius** [comment]
Thanks. I already suspected something like that.

I've got an awful lot of these in the propgrid code. Since I do not use/need propgrids myself I may just disable the propgrids for the time being.

If anyone wants wxPerl with propgrids before I do helping hands are welcome.

**Comment by sciurius** [comment]
I get some missing methods from wxBitmap:
````
GDI.c:10978:15: error: ‘class wxBitmap’ has no member named ‘SetDepth’; did you mean ‘GetDepth’?
10978 |         THIS->SetDepth(depth);
      |               ^~~~~~~~
      |               GetDepth
GDI.c: In function ‘void XS_Wx__Bitmap_SetHeight(PerlInterpreter*, CV*)’:
GDI.c:10996:15: error: ‘class wxBitmap’ has no member named ‘SetHeight’; did you mean ‘GetHeight’?
10996 |         THIS->SetHeight(height);
      |               ^~~~~~~~~
      |               GetHeight
GDI.c: In function ‘void XS_Wx__Bitmap_SetWidth(PerlInterpreter*, CV*)’:
GDI.c:11052:15: error: ‘class wxBitmap’ has no member named ‘SetWidth’; did you mean ‘GetWidth’?
11052 |         THIS->SetWidth(width);
      |               ^~~~~~~~
      |               GetWidth
````

The are in the 3.3 docs and removal is not mentioned in changes*.txt.

**Comment by sciurius** [comment]
`wxEVT_GRID_RANGE_SELECT` was removed in 3.1. This is not mentioned in changes*.txt.

**Comment by PBfordev** [comment]
> I get some missing methods from wxBitmap:
> ...
> The are in the 3.3 docs and removal is not mentioned in changes*.txt.

These are guarded with `WXWIN_COMPATIBILITY_3_0`, e.g. in the common version (same in ports):
https://github.com/wxWidgets/wxWidgets/blob/49c6810948f40c457e3d0848b9111627b5b61de5/include/wx/bitmap.h#L270-L275

But I could not find the mention of their deprecation either. I am not sure what is the policy for removal from the docs..

> `wxEVT_GRID_RANGE_SELECT` was removed in 3.1. This is not mentioned in changes*.txt.

I can still see unguarded alias defines 
https://github.com/wxWidgets/wxWidgets/blob/49c6810948f40c457e3d0848b9111627b5b61de5/include/wx/generic/grid.h#L3605-L3610

The aliasing is mentioned in the `wxGridRangeSelectEvent` docs, but not in the changelog (only that the two new events were added).

**Comment by sciurius** [comment]
Finally managed to eliminate all deprecations and I'm glad to announce that the upcoming version of wxPerl will build and run with the upcominig version of wxWidgets without the need for additional compatibilities.

It comes at a price, though. I needed to branch off the 3.2 code since the toolchain that is used to build wxPerl could not deal with constructs like
````
#if WXPERL_W_VERSION_LT( 3, 3, 0 )
void Method( int flags );
#else
void Method( wxPGVBFlags flags );
#endif
````

**Comment by sciurius** [comment]
Well, never say never...

It turned out pretty straighforward to restore 3.2 and 3.3.0 support in the cleaned up 3.3.1 version. So now it is a single codebase again, supporting everything from 2.8 up to 3.3.x dev.

**Comment by vadz** [comment]
Not sure what to do about `wxBitmap::SetXXX()`, they had never worked correctly AFAIK (and were never implemented in e.g. wxOSX) and don't make much sense, but we have indeed forgotten to document it in the change log. OTOH perhaps we can just decide that the deprecation warning (that is unfortunately not given in all ports for these functions) is enough?

`wxEVT_GRID_RANGE_SELECT` is still defined, so I don't know what is the problem with it?

**Comment by sciurius** [comment]
I'm not quite sure what went wrong with `wxEVT_GRID_RANGE_SELECT`, probably a mistake from my side.
Sorry for that, it is all okay now.

**Comment by vadz** [comment]
OK, thanks, AFAICS all the rest of the issues have been fixed too, so I guess this can be closed?

**Comment by sciurius** [comment]
Yes indeed. Thanks for your support!

**Comment by PBfordev** [comment]
> Not sure what to do about `wxBitmap::SetXXX()`, they had never worked correctly AFAIK (and were never implemented in e.g. wxOSX) and don't make much sense, but we have indeed forgotten to document it in the change log. OTOH perhaps we can just decide that the deprecation warning (that is unfortunately not given in all ports for these functions) is enough?

But what is the documentation policy for deprecated and no longer by default available API? IMO,  it should be removed from the 3.3 docs.

**Comment by vadz** [comment]
> But what is the documentation policy for deprecated and no longer by default available API? IMO, it should be removed from the 3.3 docs.

OK, done now, thanks.
