### ISSUE TITLE
Unresolved external symbols WebP

### ISSUE THREAD

**Issue by G-e-n-e-v-e-n-s-i-S** [wxWidgets/wxWidgets#25689]
### Build System Used

I build wxWidgets and/or my application using:

CMake through MSVS 2022

### Description

(Massive noob here)
After upgrading from 3.2.7 to 3.3.1 using vcpkg, I get the following errors when trying to build my app:
```
unresolved external symbol __imp_getaddrinfo
unresolved external symbol __imp_freeaddrinfo
```
in file `wxbase33u_net.lib (sckaddr.cpp.obj)`

as well as:
```
unresolved external symbol WebPFree
unresolved external symbol WebPGetDecoderVersion
unresolved external symbol WebPDecodeRGBA
unresolved external symbol WebPDecodeRGBInto
unresolved external symbol WebPGetFeaturesInternal
unresolved external symbol WebPDemuxInternal
unresolved external symbol WebPDemuxDelete
unresolved external symbol WebPDemuxGetI
unresolved external symbol WebPDemuxGetFrame
unresolved external symbol WebPDemuxReleaseIterator
unresolved external symbol WebPAnimDecoderOptionsInitInternal
unresolved external symbol WebPAnimDecoderNewInternal
unresolved external symbol WebPAnimDecoderGetInfo
unresolved external symbol WebPAnimDecoderGetNext
unresolved external symbol WebPAnimDecoderHasMoreFrames
unresolved external symbol WebPAnimDecoderReset
unresolved external symbol WebPAnimDecoderDelete
unresolved external symbol WebPEncodeRGB
unresolved external symbol WebPEncodeRGBA
unresolved external symbol WebPEncodeLosslessRGB
unresolved external symbol WebPEncodeLosslessRGBA
```
in file `wxmsw33u_core.lib (imagwebp.cpp.obj)`

### Platform and version information

- wxWidgets version  you are building: 3.3.1
- wxWidgets port  you are building: wxMSW (x64-release-static)
- OS  and its version: Windows 10
- Compiler  being used: MSVS 2022
- Non-default compiler options, if any :

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
Adding
```
  find_package(webp REQUIRED)
  target_link_libraries(${PROJECT_NAME} ${WEBP_LIBRARIES})
```

to the `CMakeLists.txt` file made the `WebP` errors go away, but the `__imp_addrinfo` ones remain.

**Comment by PBfordev** [comment]
You need to report vcpkg issues to vcpkg repo, the port is not maintained by wxWidgets devs.

FWIW, the dependency is there:
https://github.com/microsoft/vcpkg/blob/d30fdf55cfca16e12bc3ad99cbc615997014b61b/ports/wxwidgets/vcpkg.json#L34
https://github.com/microsoft/vcpkg/blob/d30fdf55cfca16e12bc3ad99cbc615997014b61b/ports/wxwidgets/portfile.cmake#L103

**Comment by MaartenBent** [comment]
Do you maybe use [FindwxWidgets](https://cmake.org/cmake/help/latest/module/FindwxWidgets.html) without specifying `CONFIG` mode?
Without `CONFIG` it uses the `FindwxWidgets.cmake` module provided by CMake, and that is not up-to-date with the latest dependencies (webp, winsock2).
With `CONFIG`. it uses the scripts from wxWidgets (though I don't know if those are available/installed with vcpkg).

`__imp_addrinfo` is part of the winsock2 library, and you'll need to link with `ws2_32`.

**Comment by PBfordev** [comment]
> Do you maybe use [FindwxWidgets](https://cmake.org/cmake/help/latest/module/FindwxWidgets.html) without specifying `CONFIG` mode? 

While possible culprit, doing that would be against vcpkg usage guideline, see
https://github.com/microsoft/vcpkg/blob/d30fdf55cfca16e12bc3ad99cbc615997014b61b/ports/wxwidgets/usage#L3

OTOH, the example bundled vcpkg for some reason calls `find_package(wxWidgets)` twice, first time without `CONFIG`?!
https://github.com/microsoft/vcpkg/blob/d30fdf55cfca16e12bc3ad99cbc615997014b61b/ports/wxwidgets/example/CMakeLists.txt#L7-L15

**Comment by MaartenBent** [comment]
> twice, first time without CONFIG?!

Yeah, weird. Seems like it's building two applications `main` and `main2` trying both methods.
With wx3.2 that might be fine, but with static wx3.3 you likely get the issue reported here.

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
I have added `CONFIG` to the following line:
`find_package(wxWidgets 3.3.1 CONFIG REQUIRED COMPONENTS core base net html)`

I am now getting an error on a subsequent line:
`include(${wxWidgets_USE_FILE})`
"include called with wrong number of arguments. include() only takes one file."

Here is my CMakeLists.txt file:

[CMakeLists.txt](https://github.com/user-attachments/files/21699768/CMakeLists.txt)

**Comment by PBfordev** [comment]
> Here is my CMakeLists.txt file:

I don't understand why you do not follow the vcpkg usage, I even linked it for you before. Here is it again:
https://github.com/microsoft/vcpkg/blob/master/ports/wxwidgets/usage

There is no `include(${wxWidgets_USE_FILE})` there, as this not used in `CONFIG` mode.

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
> I don't understand why you do not follow the vcpkg usage, I even linked it for you before.

because I have ABSOLUTELY NO IDEA what's going on :)

**Comment by PBfordev** [comment]
> I have ABSOLUTELY NO IDEA what's going on

Well, that is one more reason to follow (a) the docs (here the usage file) and (b) the advice people give you.

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
> Well, that is one more reason to follow (a) the docs (here the usage file) and (b) the advice people give you.

I am trying so hard to do this, it's just that I am so out of my depth that I can't even recognize what constitutes relevant documentation to my problem.

**Comment by MaartenBent** [comment]
With `CONFIG` mode there are no other includes or defines needed (all of the stuff from [FindwxWidgets](https://cmake.org/cmake/help/latest/module/FindwxWidgets.html) is basically irrelevant now, except the import target `wxWidgets::wxWidgets`.

In many cases you'll only need these two lines:
```cmake
find_package(wxWidgets CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE wxWidgets::wxWidgets)
```

Or if you want to keep using components like you do now:
```cmake
find_package(wxWidgets 3.3.1 CONFIG REQUIRED COMPONENTS core base net html)
target_link_libraries(${PROJECT_NAME} PRIVATE wx::core wx::base wx::net wx::html)
```

No more `wxWidgets_USE_FILE`/`wxWidgets_INCLUDE_DIRS`/`wxWidgets_LIBRARIES`/`wxWidgets_DEFINITIONS`. (`wxWidgets_LIBRARIES` still exists, but for backwards compatibility).
 Good luck!

**Comment by G-e-n-e-v-e-n-s-i-S** [comment]
Deleting the `include` line and consolidating all the `target_link_libraries` lines into one has done the trick!

Thanks MaartenBent and PBfordev for your patience and guidance.

**Comment by MaartenBent** [comment]
I created a MR over at CMake that updates the required libraries: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/11190
