### PR TITLE
2026-01 backports to 3.2

### PR DESCRIPTION
**Pull request by vadz**
As usual, please comment to point out more commits to add to this PR.

### CODE REVIEW

**Comment by nobugshere** [comment]
Would it be possible to add this one, please?  #25767

**Comment by vadz** [comment]
> Would it be possible to add this one, please? #25767

Unfortunately these changes don't apply to 3.2 cleanly, someone would need to resolve the conflicts (which shouldn't be that difficult, from a quick look at them) and check that everything works as expected in 3.2 and I can't do the latter because I don't have macOS 26.

**Comment by sl1pkn07** [comment]
Hi

i'm not sure when is out, but seems branch 3.3 have fixes for build with Qt6 wich is not backported to 3.2.9

is possible backpot it?
greetings

**Comment by vadz** [comment]
Sorry, not sure what do you mean exactly (which commit or at least which issue?).

**Comment by sl1pkn07** [comment]
3.2.9 fails build with Qt6 due 
```
[ 47%] Building CXX object libs/core/CMakeFiles/wxcore.dir/__/__/__/__/src/common/gaugecmn.cpp.o
En el fichero incluido desde /usr/include/qt6/QtCore/qtypeinfo.h:9,
                 desde /usr/include/qt6/QtCore/qglobal.h:45,
                 desde /usr/include/qt6/QtCore/qcompare.h:12,
                 desde /usr/include/qt6/QtGui/qfont.h:7,
                 desde /usr/include/qt6/QtGui/QFont:1,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/fontutil.h:29,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/fontmap.h:23,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/src/common/appcmn.cpp:45:
/usr/include/qt6/QtCore/qcontainerfwd.h:39:28: error: conflicting declaration of template ‘template<class T> using QVector = QList<T>’
   39 | template<typename T> using QVector = QList<T>;
      |                            ^~~~~~~
En el fichero incluido desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/region.h:226,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/window.h:25,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/wx.h:38,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/wxprec.h:38,
                 desde /tmp/makepkg/wxwidgets-light/src/build-qt5/libs/core/CMakeFiles/wxcore.dir/cmake_pch.hxx:5,
                 desde <línea-de-órdenes>:
/tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/qt/region.h:14:25: nota: previous declaration ‘template<class T> class QVector’
   14 | template<class T> class QVector;
      |                         ^~~~~~~
```
```
[ 50%] Building CXX object libs/core/CMakeFiles/wxcore.dir/__/__/__/__/src/common/imagpnm.cpp.o
En el fichero incluido desde /usr/include/qt6/QtCore/qtypeinfo.h:9,
                 desde /usr/include/qt6/QtCore/qglobal.h:45,
                 desde /usr/include/qt6/QtCore/qcompare.h:12,
                 desde /usr/include/qt6/QtGui/qfont.h:7,
                 desde /usr/include/qt6/QtGui/QFont:1,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/fontutil.h:29,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/src/common/fontcmn.cpp:38:
/usr/include/qt6/QtCore/qcontainerfwd.h:39:28: error: conflicting declaration of template ‘template<class T> using QVector = QList<T>’
   39 | template<typename T> using QVector = QList<T>;
      |                            ^~~~~~~
En el fichero incluido desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/region.h:226,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/window.h:25,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/wx.h:38,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/wxprec.h:38,
                 desde /tmp/makepkg/wxwidgets-light/src/build-qt5/libs/core/CMakeFiles/wxcore.dir/cmake_pch.hxx:5,
                 desde <línea-de-órdenes>:
/tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/qt/region.h:14:25: nota: previous declaration ‘template<class T> class QVector’
   14 | template<class T> class QVector;
      |                         ^~~~~~~
```
```
[ 50%] Building CXX object libs/core/CMakeFiles/wxcore.dir/__/__/__/__/src/common/layout.cpp.o
En el fichero incluido desde /usr/include/qt6/QtCore/qtypeinfo.h:9,
                 desde /usr/include/qt6/QtCore/qglobal.h:45,
                 desde /usr/include/qt6/QtCore/qcompare.h:12,
                 desde /usr/include/qt6/QtGui/qfont.h:7,
                 desde /usr/include/qt6/QtGui/QFont:1,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/fontutil.h:29,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/fontmap.h:23,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/src/common/fontmap.cpp:25:
/usr/include/qt6/QtCore/qcontainerfwd.h:39:28: error: conflicting declaration of template ‘template<class T> using QVector = QList<T>’
   39 | template<typename T> using QVector = QList<T>;
      |                            ^~~~~~~
En el fichero incluido desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/region.h:226,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/window.h:25,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/wx.h:38,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/wxprec.h:38,
                 desde /tmp/makepkg/wxwidgets-light/src/build-qt5/libs/core/CMakeFiles/wxcore.dir/cmake_pch.hxx:5,
                 desde <línea-de-órdenes>:
/tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/qt/region.h:14:25: nota: previous declaration ‘template<class T> class QVector’
   14 | template<class T> class QVector;
      |                         ^~~~~~~
En el fichero incluido desde /usr/include/qt6/QtCore/qtypeinfo.h:9,
                 desde /usr/include/qt6/QtCore/qglobal.h:45,
                 desde /usr/include/qt6/QtCore/qcompare.h:12,
                 desde /usr/include/qt6/QtGui/qfont.h:7,
                 desde /usr/include/qt6/QtGui/QFont:1,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/fontutil.h:29,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/src/common/fontutilcmn.cpp:23:
/usr/include/qt6/QtCore/qcontainerfwd.h:39:28: error: conflicting declaration of template ‘template<class T> using QVector = QList<T>’
   39 | template<typename T> using QVector = QList<T>;
      |                            ^~~~~~~
En el fichero incluido desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/region.h:226,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/window.h:25,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/wx.h:38,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/wxprec.h:38,
                 desde /tmp/makepkg/wxwidgets-light/src/build-qt5/libs/core/CMakeFiles/wxcore.dir/cmake_pch.hxx:5,
                 desde <línea-de-órdenes>:
/tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/qt/region.h:14:25: nota: previous declaration ‘template<class T> class QVector’
   14 | template<class T> class QVector;
      |                         ^~~~~~~
```
```
[ 51%] Building CXX object libs/core/CMakeFiles/wxcore.dir/__/__/__/__/src/common/matrix.cpp.o
En el fichero incluido desde /usr/include/qt6/QtCore/qtypeinfo.h:9,
                 desde /usr/include/qt6/QtCore/qglobal.h:45,
                 desde /usr/include/qt6/QtGui/qtguiglobal.h:7,
                 desde /usr/include/qt6/QtGui/qpainter.h:7,
                 desde /usr/include/qt6/QtGui/QPainter:1,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/src/generic/graphicc.cpp:99:
/usr/include/qt6/QtCore/qcontainerfwd.h:39:28: error: conflicting declaration of template ‘template<class T> using QVector = QList<T>’
   39 | template<typename T> using QVector = QList<T>;
      |                            ^~~~~~~
En el fichero incluido desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/region.h:226,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/window.h:25,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/wx.h:38,
                 desde /tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/wxprec.h:38,
                 desde /tmp/makepkg/wxwidgets-light/src/build-qt5/libs/core/CMakeFiles/wxcore.dir/cmake_pch.hxx:5,
                 desde <línea-de-órdenes>:
/tmp/makepkg/wxwidgets-light/src/wxwidgets/include/wx/qt/region.h:14:25: nota: previous declaration ‘template<class T> class QVector’
   14 | template<class T> class QVector;
      |                         ^~~~~~~
```
then, searching in the tree, found this commits 

https://github.com/wxWidgets/wxWidgets/commit/e647cd0e5e0d15d834ed971d38f9c66b31ec6e11

but can't be apply with cherrypick due conflicts in `src/qt/region.cpp`

greetings

**Comment by vadz** [comment]
I think it would be enough to just replace `QVector` with `wxVector` and keep the rest of the code unchanged in 3.2, but I didn't test it. If this works for you, please make a PR for 3.2 with this change and I'll merge it.

**Comment by sl1pkn07** [comment]
sorry. but, the repo is a bit messy. i cant apply directly by cherrypinking because need a ton of them, inclusive commits commited several years ago before release 3.2.9, not included in it, but included in newer 3.3.x

so i opted to disable completely search Qt6 by

```patch
diff --git a/build/cmake/toolkit.cmake b/build/cmake/toolkit.cmake
index 0910b66d68..365f055572 100644
--- a/build/cmake/toolkit.cmake
+++ b/build/cmake/toolkit.cmake
@@ -129,7 +129,7 @@ if(UNIX AND NOT WIN32 AND (WXX11 OR WXMOTIF OR WXGTK2 OR (WXGTK AND wxHAVE_GDK_X
 endif()
 
 if(WXQT)
-    find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Core)
+    find_package(QT NAMES Qt5 REQUIRED COMPONENTS Core)
 
     if(QT_VERSION_MAJOR EQUAL 5)
         set(QT_COMPONENTS Core Widgets Gui OpenGL OpenGL Test)
```

greetings

**Comment by moi15moi** [comment]
As said [here](https://github.com/wxWidgets/wxWidgets/pull/26078#pullrequestreview-3639704850), could you add it?

**Comment by vadz** [comment]
> sorry. but, the repo is a bit messy. i cant apply directly by cherrypinking because need a ton of them, inclusive commits commited several years ago before release 3.2.9, not included in it, but included in newer 3.3.x

This seems doubtful. More likely is that they had been included in 3.3 but then were changed there.

> so i opted to disable completely search Qt6 by

@AliKet is the de facto wxQt maintainer, so I'll let him decide whether this should be done or not. If Qt6 build is really that difficult to fix, it probably is...

**Comment by MaartenBent** [comment]
Before 3.2.9 CMake only looked for Qt5. When I backported many CMake changes in #25998, it also included finding Qt6. Maybe this should be reverted until (and if) Qt6 changes can be backported.

**Comment by vadz** [comment]
> Before 3.2.9 CMake only looked for Qt5. When I backported many CMake changes in #25998, it also included finding Qt6. Maybe this should be reverted until (and if) Qt6 changes can be backported.

I see, thanks. If nobody backports Qt6 fixes to 3.2, I'll revert this, i.e. apply the change proposed by Gustavo above.
