### ISSUE TITLE
wxMemoryDC::SetFont( wxNullFont ) crashes under MSW

### ISSUE THREAD

**Issue by taler21** [wxWidgets/wxWidgets#22240]
This bug was introduced with commit [9e5c8a802700f3fef6c1fda6d3b375e3e21e42cc](https://github.com/wxWidgets/wxWidgets/commit/9e5c8a802700f3fef6c1fda6d3b375e3e21e42cc).

A possible fix would be:
```patch
diff --git "a/src/msw/dcmemory.cpp" "b/src/msw/dcmemory.cpp"
index 9d7c52b531..ae7007f15e 100644
--- "a/src/msw/dcmemory.cpp"
+++ "b/src/msw/dcmemory.cpp"
@@ -148,7 +148,8 @@ void wxMemoryDCImpl::SetFont(const wxFont& font)
     // We need to adjust the font size by the ratio between the scale factor we
     // use and the default/global scale factor used when creating fonts.
     wxFont scaledFont = font;
-    scaledFont.WXAdjustToPPI(wxDisplay::GetStdPPI()*m_contentScaleFactor);
+    if (scaledFont.IsOk())
+        scaledFont.WXAdjustToPPI(wxDisplay::GetStdPPI()*m_contentScaleFactor);
     wxMSWDCImpl::SetFont(scaledFont);
 }
 

```

**Platform and version information**
 - wxWidgets version you use: **Latest master** of upcoming 3.1.6
 - wxWidgets port you use: **wxMSW**
 - OS and its version: Windows 10

**Comment by vadz** [comment]
Thanks a lot for noticing and reporting this! Will be fixed when the PR above is merged.

**Comment by vadz** [comment]
Hmm, it seems like this hadn't worked even before in non-MSW ports. Still should probably be fixed in wxMSW, but it looks like we don't actually support calling `SetFont(wxNullFont)`.

**Comment by taler21** [comment]
> Hmm, it seems like this hadn't worked even before in non-MSW ports. Still should probably be fixed in wxMSW, but it looks like we don't actually support calling `SetFont(wxNullFont)`.

I don't think so. I use code and libraries that call `SetFont(wxNullFont)` also with wxGTK and haven't had any problems so far.
In addition, it is even explicitly mentioned in the official documentation (e.g. of wxWidgets-3.1.5):
```cpp
/**
    Sets the current font for the DC.

    If the argument is ::wxNullFont (or another invalid font; see wxFont::IsOk),
    the current font is selected out of the device context (leaving wxDC without
    any valid font), allowing the current font to be destroyed safely.

    @see wxFont
*/
void SetFont(const wxFont& font);
```

Maybe you just mean that `wxDC::GetTextExtent(...)` doesn't work if no valid font is set?
In this case I would think that on the one hand this is to be expected and on the other hand it makes no sense to call `GetTextExtent(...)` without a valid font.

**Comment by vadz** [comment]
I've seen the docs, but they're very MSW-specific and don't really make sense, so I've [updated them](https://docs.wxwidgets.org/latest/classwx_d_c.html#afab18239d707cd403235b36a987171a8) now to better correspond to the reality.

And yes, it's true that `SetFont()` on its own succeeds, but as neither `GetTextExtent()` nor `DrawText()` work after it, while all the other functions don't use the font at all, I don't see any point in doing it. I.e. calling `SetFont(wxNullFont)` is at best useless under non-MSW and in wxMSW it does something that you almost certainly don't want, as it resets the font to the default one carried over from Windows 3.1 days that you never want to see.

Thinking more about this, I really think we should assert in `SetFont()` that the font is valid. Or is there some good reason to call it with an invalid font that I'm missing?

**Comment by taler21** [comment]
Based on previous documentation (up to and including wxWidgets-3.1.5) I thought it is best practice to call `SetFont(wxNullFont)` after drawing text is completed.
But I obviously misinterpreted the documentation.
So what would actually be best practice?

If calling `SetFont(wxNullFont)` is no longer supported, this must be reported as an **incompatible change** in the change log at **Changes in behaviour not resulting in compilation errors**.

Be aware that this change (assert in `SetFont()` that the font is valid) will break existing code.
Not only my code. There are also third-party libraries (at least wxArt2D, probably more) that also call `SetFont(wxNullFont)`.
It's even used in wxWidgest itself. See [wxDragImage::Create(...)](https://github.com/wxWidgets/wxWidgets/blob/228bbbf93a96b108562808bf36cacf22cabe4c1e/src/msw/dragimag.cpp#L234) for wxMSW.

In my opinion it's not worth to break existing code, since as you say `SetFont(wxNullFont)` works on its own.
Maybe only change the documentation (again) to say that calling `SetFont(wxNullFont)` is possible, but functions using the font like `GetTextExtent()` or `DrawText()` doesn't work without a valid font?

**Comment by vadz** [comment]
> Based on previous documentation (up to and including wxWidgets-3.1.5) I thought it is best practice to call `SetFont(wxNullFont)` after drawing text is completed. But I obviously misinterpreted the documentation. So what would actually be best practice?

You didn't misinterpret it, the documentation was simply wrong, sorry about that.

> If calling `SetFont(wxNullFont)` is no longer supported, this must be reported as an **incompatible change** in the change log at **Changes in behaviour not resulting in compilation errors**.

Yes, absolutely. But we're probably not going to change this for the reasons you point out.
 
> Be aware that this change (assert in `SetFont()` that the font is valid) will break existing code. Not only my code. There are also third-party libraries (at least wxArt2D, probably more) that also call `SetFont(wxNullFont)`. It's even used in wxWidgest itself. See [wxDragImage::Create(...)](https://github.com/wxWidgets/wxWidgets/blob/228bbbf93a96b108562808bf36cacf22cabe4c1e/src/msw/dragimag.cpp#L234) for wxMSW.

Indeed, thanks for pointing this out.
 
> In my opinion it's not worth to break existing code, since as you say `SetFont(wxNullFont)` works on its own. Maybe only change the documentation (again) to say that calling `SetFont(wxNullFont)` is possible, but functions using the font like `GetTextExtent()` or `DrawText()` doesn't work without a valid font?

Yes, I agree. I think the current docs are fine, i.e. they discourage calling it with the invalid font, but still allow it under MSW.
