### ISSUE TITLE
missing symbols in html library when built with libmspack

### ISSUE THREAD

**Issue by antonio-rojas** [wxWidgets/wxWidgets#26019]
#### Bug description:

If 3.2.9 is compiled with libmspack support on Linux, the html library is missing symbols.

#### To Reproduce:

```
$ g++ -x - $(wx-config --libs html)
[...]
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/15.2.1/../../../../lib/libwx_gtk3u_html-3.2.so: undefined reference to `_wx_link_dummy_func_wxhtml_chm_support()'
```

This is caused by 2db5b45971748d7830e486147d9e5597de103666, specifically by this change:
```
diff --git a/build/cmake/lib/html/CMakeLists.txt b/build/cmake/lib/html/CMakeLists.txt
index 3fd0ebd0413c..7a19d45c89b7 100644
--- a/build/cmake/lib/html/CMakeLists.txt
+++ b/build/cmake/lib/html/CMakeLists.txt
@@ -9,7 +9,7 @@

 wx_append_sources(HTML_FILES HTML_CMN)

-if(WIN32 OR wxUSE_LIBMSPACK)
+if(WXMSW)
     wx_append_sources(HTML_FILES HTML_MSW)
 endif()
```

### Platform and version information

- wxWidgets version  you use: 3.2.9
- wxWidgets port  you use: wxGTK
- OS  and its version: Arch Linux x86_64
  
  + GTK version:  3.24.51
  + Which GDK  backend is used: Wayland
  + Desktop environment : Plasma
  + Current theme:  n/a

**Comment by MaartenBent** [comment]
My bad, I backported this without the changes to `files.cmake`. @vadz can you revert this change to `build/cmake/lib/html/CMakeLists.txt` or should I create a PR for it?

This shouldn't affect the already built binaries, these are not built using cmake.

**Comment by vadz** [comment]
@antonio-rojas Thanks for testing!

@MaartenBent I can push this, please let me know if you see anything wrong with it:

```diff
commit 4ec643da68e84652f4cb65505fafe487cabbdd14
Author: Vadim Zeitlin <vadim@wxwidgets.org>
Date:   2025-12-07 20:54:06 +0100

    Fix recently broken wxHTML build with libmspack
    
    Revert part of 2db5b45971 (Backport CMake changes, 2025-11-29) which
    broke the build in this case.
    
    Closes #26019.

diff --git a/build/cmake/lib/html/CMakeLists.txt b/build/cmake/lib/html/CMakeLists.txt
index 7a19d45c89..c4d6e2172e 100644
--- a/build/cmake/lib/html/CMakeLists.txt
+++ b/build/cmake/lib/html/CMakeLists.txt
@@ -9,7 +9,7 @@
 
 wx_append_sources(HTML_FILES HTML_CMN)
 
-if(WXMSW)
+if(WXMSW OR wxUSE_LIBMSPACK)
     wx_append_sources(HTML_FILES HTML_MSW)
 endif()
 
```

**Comment by MaartenBent** [comment]
Yes, that should be fine. Thanks.

**Comment by vadz** [comment]
Fixed in the commit above.
